calenderの課題を作成しました
manabuno2/ruby-practices pull request #1
Opened 2022-07-05 16:00 UTC by manabuno2

コードレビューをお願いします！

2022-07-10 07:47 UTC, func09 requested changes
確認しました！

2022-07-10 07:47 UTC, func09 commented on 02.calendar/cal.rb
> +puts "\n"
day_of_week の全要素に 半角スペースを入れてあるのが気になりました。
例えば

```ruby
day_of_week = [ '日', '月', '火', '水', '木', '金', '土']
puts day_of_week.join(" ")
```

こんな感じで、配列にスペースをいれつつ結合することができます。ご参考までに。

2022-07-10 07:47 UTC, func09 commented on 02.calendar/cal.rb
> +(start_cwday).times do #その月の1日の曜日以前をブランクを挿入する
```suggestion
start_cwday.times do #その月の1日の曜日以前をブランクを挿入する
```

ここはカッコ不要ですね。

2022-07-10 07:47 UTC, func09 commented on 02.calendar/cal.rb
> +  end
なるほどー、１桁の数字だった場合のスペース埋めをしているんですね

2022-07-10 07:47 UTC, func09 commented on 02.calendar/cal.rb
> +  end
Rubyだと他には `sprintf` を使ったり `rjust` でよりスマートにかけます。ご参考までに
https://docs.ruby-lang.org/ja/latest/method/String/i/=25.html
https://docs.ruby-lang.org/ja/latest/method/String/i/rjust.html

```ruby
sprintf("%2d", x.day)
x.day.to_s.rjust(2)
```

2022-07-10 07:47 UTC, func09 commented on 02.calendar/cal.rb
> +  if x.saturday?
<img width="490" alt="Cursor_と_-zsh" src="https://user-images.githubusercontent.com/34449/178135984-220f81af-c340-4daf-b1d1-c641c18d6318.png">

土曜日のところで改行をいれるのは良いと思います。

最終日の後も改行が入るように修正してみてほしいです！

2022-07-11 13:58 UTC, manabuno2 commented on 02.calendar/cal.rb
> +puts "\n"
ありがとうございます！ .join メソッドはこうやって使うのか、と納得しました。反映しました！

2022-07-11 13:59 UTC, manabuno2 commented on 02.calendar/cal.rb
> +  end
`rjust` 使ってみました！参考になります。

2022-07-11 13:59 UTC, manabuno2 commented on 02.calendar/cal.rb
> +  if x.saturday?
変更を反映しました！

2022-07-12 03:32 UTC, func09 approved these changes
LGTMです〜 🎉 🎉

2022-07-12 03:32 UTC, func09 commented on 02.calendar/cal.rb
> +    puts "\n"
👍

2022-07-12 06:50 UTC, merged